### ISSUE TITLE
Add Hugo's code as unit tests

### ISSUE THREAD

**Issue by wleoncio** [tmatta/lsasim#30]
# Summary

Some closed issues are missing future-proofing w.r.t. Hugo's report.

# Unit tests to add

- Add tests based on errors that were handled
- Add tests based on OK output?

# Issues to add tests to

- [x] Add unit tests to issue #13 
- [x] Add unit tests to issue #14 
- [x] Add unit tests to issue #15 
- [x] Add unit tests to issue #16
